#!/usr/bin/env php
<?php

umask(0000);
set_time_limit(0);

require_once __DIR__.'/app/bootstrap.php';

use Hyperion\Workflow\Engine\WorkflowApplication;
use Symfony\Component\Console\Input\ArgvInput;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', '')) && $env !== 'prod';

$application = new WorkflowApplication($env, $debug);
$application->run($input);
