imports:
    - { resource: config.yml }

parameters:
    # For the Hyperion data-provider
    hyperion.dbal:
        hostname:  api.hyperion.dev

    # Workflow cache pool
    hyperion.cache-pool: tcp://127.0.0.1:6379

