services:
    hyperion.dbal:
        class: Hyperion\Dbal\DataManager
        factory_class: Hyperion\Workflow\Factory\DataManagerFactory
        factory_method: get
        arguments: [ %hyperion.dbal% ]
    hyperion.workflow_manager:
        class: Hyperion\Workflow\Services\WorkflowManager
        arguments: [ %hyperion.workflow% ]
