services:
    hyperion.cache_pool:
        class: Bravo3\Cache\Redis\RedisCachePool
        arguments: [ %hyperion.cache-pool% ]
    hyperion.data_manager:
        class: Hyperion\Dbal\DataManager
        factory_class: Hyperion\Workflow\Factory\DataManagerFactory
        factory_method: get
        arguments: [ %hyperion.dbal% ]
    hyperion.stack_manager:
        class: Hyperion\Dbal\StackManager
        factory_class: Hyperion\Workflow\Factory\StackManagerFactory
        factory_method: get
        arguments: [ %hyperion.dbal% ]
    hyperion.command_driver:
        class: Hyperion\Workflow\Services\CommandManager
        arguments: [ '@hyperion.data_manager', '@hyperion.cache_pool' ]
    hyperion.decision_manager:
        class: Hyperion\Workflow\Services\DecisionManager
        arguments: [ %swf%, %hyperion.workflow%, '@hyperion.data_manager', '@hyperion.stack_manager', '@hyperion.cache_pool' ]
    hyperion.work_manager:
        class: Hyperion\Workflow\Services\WorkManager
        arguments: [ %swf%, %hyperion.workflow%, '@hyperion.command_driver' ]
